### PR TITLE
Update to use new optparse-applicative

### PR DESCRIPTION
**Pull request by oswynb**
Helps with building with many other packages which use newer versions (or have dependencies which do), one specific example being hasql-postgres.

### CODE REVIEW

**Comment by nikita-volkov** [comment]
I've messed around with Travis after your PR a little, and I just can't fix it. This library needs an update of the Criterion dependency, which unfortunately I won't have any time to do any time soon.

**Comment by oswynb** [comment]
I was messing around with trying to update that as well, don't have a lot of time but I might take a swing at that as well and make another PR.

**Comment by nikita-volkov** [comment]
BTW, some major updates to the "hasql" ecosystem are coming and the new versions are likely to be using "criterion" directly.

**Comment by oswynb** [comment]
Righto. Took a crack and I'm unsure I'd be able to reasonably update criterion-plus and preserve functionality. Good to hear about the updates!

**Pull request closed without merging**
